pipeline:
  build:
    image: ${IMAGE}
    commands:
      - go build

  test:
    image: ${IMAGE}
    commands:
      - go test

matrix:
  IMAGE:
    - golang:1.7
    - golang:1.8
    - golang:latest
