pipeline:
  build:
    image: ${IMAGE}
    commands:
      - go build

  test:
    image: ${IMAGE}
    commands:
      - go test

  publish:
    image: plugins/docker
    repo: josebarn/hello-world
    tags: [ 1.0.0, 1.0, latest ]
    dockerfile: ./docker/Dockerfile
    secrets: [ docker_username, docker_password ]
    debug: true
matrix:
  IMAGE:
    - golang:latest
