# NOTE: Refer drone Go example http://readme.drone.io/0.5/usage/golang-example/
workspace:
  base: /go
  path: src/github.com/josebarn/drone-with-go

pipeline:
  build:
    image: golang
    script:
      - go get
      - go build

  unit-test:
    image: golang
    commands:
      - go test ./api

  publish:
    image: plugins/docker
    repo: josebarn/hello-world
    tags: [ 1.0.0, 1.0, latest ]
    dockerfile: ./docker/Dockerfile
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
#    debug: true
