pipeline:
  build:
    image: ${IMAGE}
    commands:
      - go build

  unit-test:
    image: ${IMAGE}
    commands:
      - go test ./api

  publish:
    image: plugins/docker
    repo: josebarn/hello-world
    tags: [ 1.0.0, 1.0, latest ]
    dockerfile: ./docker/Dockerfile
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    debug: true
matrix:
  IMAGE:
    - golang:latest
