version: '2'

services:

  app:
    container_name: "hello"
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
     - "3000:3000"
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
